/* summary-map.js
 * Embedded Adobe automation summary mapping (source: 'Adobe Automation- A11y Hawks.xlsx').
 * For each automation rule: the OLD axe-generated summary, the corrected NEW Adobe
 * summary, and the expected NEW Expected Results / Actual Results / Remediation text.
 * Text is preserved verbatim from the source sheet. Regenerate from the sheet when it changes.
 */
const SUMMARY_MAP = [
  {
    checkpoint: "1.1.1 a",
    oldSummary: "[role=\"img\"] elements must have an alternative text",
    newSummary: "Text alternative for the active image missing",
    expectedResults: "Text alternativeis provided the above mentioned active image(s).",
    actualResults: "Text alternative is missing for the above mentioned active image(s).",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1. Use the alt attribute on the \u003cimg\u003e element to convey the destination, purpose, or function of the image.\n\n\u003ca href=\"index.html\"\u003e\u003cimg src=\"ABCD-logo.png\" alt=\"ABCD Home\"\u003e\u003c/a\u003e\n\n2. Use the aria-label attribute to convey the destination, purpose, or function of the image.\n\n\u003cbutton class=\"infoicon\" aria-label=\"more information\"\u003e\u003c/button\u003e\n\n\u003ca href=\"javascript:alert(\u0027Warning!\u0027);\" aria-label=\"warning\"\u003e\n\u003csvg focusable=\"false\"\u003e\n\u003cuse xlink:href=\"#warning\"\u003e\u003c/use\u003e\n\u003c/svg\u003e\n\u003c/a\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/images/alt-text/actionable-links-buttons\nW3C-WAI tutorial: https://www.w3.org/WAI/tutorials/images/",
  },
  {
    checkpoint: "1.1.1 b",
    oldSummary: "Images must have alternative text",
    newSummary: "Text alternative for the informative image is missing",
    expectedResults: "Text alternative is provided for the above mentioned informative image(s).",
    actualResults: "Text alternative is missing for the above mentioned informative image(s).",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1. Use the alt attribute on the \u003cimg\u003e element to convey the intent, purpose, or meaning of the image.\n\n\u003cimg src=\"sunset.jpg\" alt=\"The sun setting over the Pacific Ocean, with a silhouette of a flying seagull in the foreground\"\u003e\n\n\u003cimg src=\"cat.svg\" alt=\"cat\" role=\"img\"\u003e (role is optional, for backwards compatibility with Safari)\n\n2. Use aria-label and role=\"img\" to convey the intent, purpose, or meaning of the image.\n\n\u003cp\u003eHave a great day \u003cspan class=\"fonticon smiley\" role=\"img\" aria-label=\"Smiley face\"\u003e\u003c/span\u003e\u003c/p\u003e\n\n\u003csvg role=\"img\" aria-label=\"cat\"\u003e\n\n3. Use CSS clipped text to provide screen reader accessible (non-visible) alternative text.\n\n\u003ca href=\"https://www.facebook.com/dequesystems\" class=\"fb\"\u003e\n\u003cspan class=\"sr-text\"\u003eDeque\u0027s Facebook page\u003c/span\u003e\n\u003c/a\u003e\n\n.sr-text {\nposition: absolute;\nclip: rect(1px, 1px, 1px, 1px);\n-webkit-clip-path: inset(50%) ;\nclip-path: inset(50%);\npadding: 0;\nborder: 0;\nheight: 1px;\nwidth: 1px;\nwhite-space: nowrap;\noverflow: hidden;\n}\n\nReference: \nDeque University: https://dequeuniversity.com/class/images/alt-text/informative\nW3C-WAI tutorial: https://www.w3.org/WAI/tutorials/images/",
  },
  {
    checkpoint: "1.3.1 a",
    oldSummary: "Certain ARIA roles must contain particular children",
    newSummary: "ARIA roles does not contain required children roles",
    expectedResults: "The above-mentioned element(s) with [PLACEHOLDER – ADD THE CURRENT PARENT ROLE] is provided with the required [PLACEHOLDER – ADD THE MISSING CHILD ROLE].",
    actualResults: "The above-mentioned element(s) with [PLACEHOLDER – ADD THE CURRENT PARENT ROLE] is missing the required [PLACEHOLDER – ADD THE MISSING CHILD ROLE].",
    remediation: "Ensure all ARIA roles have their required children elements, if any.\n\nReference: \nWAI-ARIA Specification - The Roles Model - https://www.w3.org/TR/wai-aria-1.1/#roles\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "1.3.1 a",
    oldSummary: "Certain ARIA roles must be contained by particular parents",
    newSummary: "ARIA roles does not contain required parent roles",
    expectedResults: "The above-mentioned element(s) with [PLACEHOLDER – ADD THE CURRENT ROLE] is provided with the required [PLACEHOLDER – ADD THE MISSING PARENT ROLE].",
    actualResults: "The above-mentioned element(s) with [PLACEHOLDER – ADD THE CURRENT ROLE] is missing the required [PLACEHOLDER – ADD THE MISSING PARENT ROLE].",
    remediation: "Ensure all ARIA roles are contained by their required parent element, if any.\n\nReference: \nWAI-ARIA Specification - The Roles Model - https://www.w3.org/TR/wai-aria-1.1/#roles\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "1.3.1 f",
    oldSummary: "\u003cli\u003e elements must be contained in a \u003cul\u003e or \u003col\u003e",
    newSummary: "The \u003cli\u003e list item elements are not contained in a \u003cul\u003e or \u003col\u003e",
    expectedResults: "The above-mentioned \u003cli\u003e element(s) is contained within a \u003cul\u003e or \u003col\u003e element.",
    actualResults: "The above-mentioned \u003cli\u003e element(s) is not contained within a \u003cul\u003e or \u003col\u003e element.",
    remediation: "Fix this issue by correctly applying \u003cul\u003e/\u003cli\u003e or \u003col\u003e/\u003cli\u003e markup.\n1. Unordered list: Wrap a series of list items (\u003cli\u003e) inside an unordered list element (\u003cul\u003e). Unordered lists should be used when a set of items can be placed in any order.\n\n\u003cul\u003e\n\u003cli\u003eStrawberries\u003c/li\u003e\n\u003cli\u003ePapaya\u003c/li\u003e\n\u003cli\u003eMangos\u003c/li\u003e\n\u003cli\u003eKiwis\u003c/li\u003e\n…\n\u003c/ul\u003e\n\n2. Ordered list: Wrap a series of list items (\u003cli\u003e) inside an ordered list element (\u003col\u003e). Ordered lists should be used when the list items need to be placed in a specific order.\n\n\u003ch3\u003eHow to boil an egg\u003c/h3\u003e\n\u003col\u003e\n\u003cli\u003ePlace eggs in a large saucepan.\u003c/li\u003e\n\u003cli\u003eCover them with cool water by 1 inch.\u003c/li\u003e\n\u003cli\u003eCover pan with a lid and bring water to a rolling boil over high heat.\u003c/li\u003e\n\u003cli\u003eWhen the water has reached a boil, remove saucepan from the burner.\u003c/li\u003e\n\u003cli\u003eLet eggs sit in water for 12 minutes.\u003c/li\u003e\n\u003c/ol\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/lists/semantic-markup\nW3C-WAI tutorial: https://www.w3.org/WAI/tutorials/page-structure/content/#lists",
  },
  {
    checkpoint: "1.3.1 f",
    oldSummary: "\u003cul\u003e and \u003col\u003e must only directly contain \u003cli\u003e, \u003cscript\u003e or \u003ctemplate\u003e elements",
    newSummary: "The \u003cul\u003e and \u003col\u003e list markup elements directly contain \u003cli\u003e",
    expectedResults: "The above-mentioned \u003cul\u003e or \u003col\u003e element(s) contain only permitted direct child element(s).\n\n[PLACEHOLDER ADD THE VALID CHILD ELEMENT]",
    actualResults: "The above-mentioned \u003cul\u003e or \u003col\u003e element(s) contains invalid direct child element(s).\n\n[PLACEHOLDER ADD THE INVALID CHILD ELEMENT]",
    remediation: "Fix this issue by ensuring that all ordered and unordered lists (defined by ul or ol elements) contain only \u003cli\u003e, \u003cscript\u003e or \u003ctemplate\u003e elements as direct children.\n\nReference: \nDeque University:https://dequeuniversity.com/class/semantic-structure/lists/semantic-markup",
  },
  {
    checkpoint: "1.4.1 b",
    oldSummary: "Links are not distinguishable without relying on color",
    newSummary: "Link contrast is not at least 3:1 with surrounding text",
    expectedResults: "The above-mentioned link element(s) meets the required 3:1 contrast ratio against the surrounding text.",
    actualResults: "The above-mentioned link element(s) do not meet the required 3:1 contrast ratio against the surrounding text.\n\n[PLACEHOLDER ADD CONTRAST DETAILS]",
    remediation: "Fix this issue by using ONE of the following techniques:-\n1. Leave the link text and body text contrast as-is, but add an additional indicator (e.g. underline, outline, etc.) to the link text when it is in its default state.\n2. Increase the contrast between the link text and the body text so that the ratio is at least 3.0 to 1.\n\nReference: \nDeque University: https://dequeuniversity.com/class/visual-design/color/distinguish-links-from-text\nWCAG Technique G183: Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on focus for links or controls where color alone is used to identify them: https://www.w3.org/TR/WCAG20-TECHS/G183.html",
  },
  {
    checkpoint: "1.4.3",
    oldSummary: "Elements must meet minimum color contrast ratio thresholds",
    newSummary: "Text content lacks 4.5:1 contrast ratio",
    expectedResults: "The above-mentioned text element(s) meets the required 4.5:1 color contrast ratio.",
    actualResults: "The above-mentioned text element(s) do not meet the required 4.5:1 color contrast ratio.\n\n[PLACEHOLDER ADD CONTRAST DETAILS]",
    remediation: "Fix this issue by adjusting the text and/or background to increase the contrast to at least 4.5 to 1.\n\nReference: \nDeque University: https://dequeuniversity.com/class/visual-design/contrast/text-against-background",
  },
  {
    checkpoint: "1.4.4",
    oldSummary: "Zooming and scaling must not be disabled",
    newSummary: "Zooming and scaling is disabled",
    expectedResults: "Zooming and scaling are enabled on the above-mentioned page.",
    actualResults: "Zooming and scaling are disabled on the above-mentioned page.",
    remediation: "Fix the issue by ensuring the zooming and scaling functionality is not disabled.",
  },
  {
    checkpoint: "2.1.1",
    oldSummary: "Scrollable region must have keyboard access",
    newSummary: "Scrollable region does not have keyboard access",
    expectedResults: "The above-mentioned scrollable region(s) is keyboard accessible.",
    actualResults: "The above-mentioned scrollable region(s) is not keyboard accessible.",
    remediation: "Fix this issue by ensuring the component can be used by the keyboard. This includes ensuring controls are:\n1. Focusable with a keyboard (i.e. can be reached using the Tab key or Arrow keys on a keyboard), and\n2. Operable with a keyboard (e.g. links are activated with the Enter key, buttons are activated with Enter and Spacebar, checkboxes are activated with Spacebar, dragging and swiping actions have a keyboard alternative, etc.)\n\nThe best way to do this is to use native HTML elements when HTML equivalents exist (e.g. anchor, button, select, text area, and input elements). When custom (non native HTML) controls have to be used, you must ensure they can be focused with a keyboard (often using tabindex=\"0\") and operated with a keyboard (using JavaScript event handlers). The ARIA Authoring Practices Guide provides information on expected keyboard interaction patterns for custom controls and widgets and working examples (see References below).\n\nReference: \nDeque University: https://dequeuniversity.com/class/input-methods/keyboard-input/functionality\nARIA Authoring Practices Guide Patterns: https://www.w3.org/WAI/ARIA/apg/patterns/",
  },
  {
    checkpoint: "2.4.2",
    oldSummary: "Documents must have \u003ctitle\u003e element to aid in navigation",
    newSummary: "The page does not have a programmatic title",
    expectedResults: "The above-mentioned page is provided with a programmatic title.",
    actualResults: "The above-mentioned page is missing a programmatic title.",
    remediation: "Fix this issue by using the \u003ctitle\u003e element in the document \u003chead\u003e to provide an accurate, informative, and (preferably) unique page title.\n\n\u003chtml lang=\"en\"\u003e\n\u003chead\u003e\n\u003ctitle\u003eProducts and Services\u003c/title\u003e\n\u003c/head\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/page-title/every-page",
  },
  {
    checkpoint: "2.5.8",
    oldSummary: "All touch targets must be 24px large, or leave sufficient space",
    newSummary: "Target does not meet minimum size or spacing",
    expectedResults: "The above-mentioned touch target element(s) meets the minimum size or spacing requirements.",
    actualResults: "The above-mentioned touch target element(s) does not meet the minimum size or spacing requirements.",
    remediation: "Fix this issue by doing at least ONE of the following:-\n\n1. Ensure that the control has a target size of at least 24 x 24 CSS px.\n\n2. Ensure that a 24 pixel diameter circle centered on the target does not touch another target nor a 24 pixel diameter circle placed on the center of any other adjacent targets that are less than 24 by 24 pixels\n\nReference: \nWCAG Understanding document: https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum",
  },
  {
    checkpoint: "3.1.1",
    oldSummary: "\u003chtml\u003e element must have a valid value for the lang attribute",
    newSummary: "The lang attribute value is not valid",
    expectedResults: "The above-mentioned page is provided with a valid lang attribute value.",
    actualResults: "The above-mentioned page contains an invalid lang attribute value.",
    remediation: "Fix this issue by providing a correct and valid lang attribute value.\n\nIn the following example, the two-letter code \"en\" specifies English as the primary language of the document. \u003chtml lang=\"en\"\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/language/primary-language",
  },
  {
    checkpoint: "3.1.1",
    oldSummary: "\u003chtml\u003e element must have a lang attribute",
    newSummary: "The lang attribute is not programmatically assigned to a page",
    expectedResults: "The above-mentioned page is provided with a programmatically assigned lang attribute.",
    actualResults: "The above-mentioned page is missing a programmatically assigned lang attribute.",
    remediation: "Fix this issue by identifying the primary language of the document in the opening \u003chtml\u003e element using the lang attribute.\n\nIn the following example, the two-letter code \"en\" specifies English as the primary language of the document. \u003chtml lang=\"en\"\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/language/primary-language",
  },
  {
    checkpoint: "3.1.2",
    oldSummary: "lang attribute must have a valid value",
    newSummary: "Value of the lang attribute is not valid",
    expectedResults: "The above-mentioned element(s) is provided with a valid lang attribute value.\n\n[PLACEHOLDER ADD CORRECT LANG VALUE]",
    actualResults: "The above-mentioned element(s) contains an invalid lang attribute value.\n\n[PLACEHOLDER ADD INCORRECT LANG VALUE]",
    remediation: "Fix this issue by providing a valid lang value for the lang attribute.\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/language/parts",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Elements must only use supported ARIA attributes",
    newSummary: "Element contains ARIA attributes not allowed for its role",
    expectedResults: "The above-mentioned element(s) uses only supported ARIA attribute(s) for its role.\n\n[PLACEHOLDER ADD SUPPORTED ROLE]",
    actualResults: "The above-mentioned element(s) contains unsupported ARIA attribute(s) for its role.\n\n\n[PLACEHOLDER ADD UNSUPPORTED ROLE]",
    remediation: "Fix this issue by using the appropriate ARIA roles, states, and properties. \n\nResource Link:\n- https://www.w3.org/TR/wai-aria-1.1/ \n- https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA commands must have an accessible name",
    newSummary: "ARIA commands are missing an accessible name",
    expectedResults: "The above-mentioned ARIA command element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned ARIA command element(s) is missing an accessible name.",
    remediation: "Fix this issue by using any of the following techniques:-\n1. Use the innertext of the \u003cbutton\u003e or role=\"button\" element\n\n\u003cbutton\u003eApply now!\u003c/button\u003e\n\n\u003cbutton class=\"apply-btn\"\u003e\u003cspan class=\"sr-text\"\u003eApply now!\u003c/span\u003e\u003c/button\u003e\n\n2. Use a non-empty aria-label attribute on the \u003cbutton\u003e or role=\"button\" element.\n\n\u003cbutton class=\"apply-btn\" aria-label=\"Apply now!\"\u003e\u003c/button\u003e\n\n\u003cspan role=\"button\" class=\"apply-btn\" aria-label=\"Apply Now!\"\u003e\u003c/span\u003e \n\nReference:\n- https://dequeuniversity.com/class/custom-widgets/concepts/name \n- https://www.w3.org/TR/wai-aria-1.1/#aria-label",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA hidden element must not be focusable or contain focusable elements",
    newSummary: "The focusable element or contain focusable elements does not contain aria-hidden=\"true\"",
    expectedResults: "The above-mentioned aria-hidden=\"true\" element(s) does not contain focusable element(s).",
    actualResults: "The above-mentioned aria-hidden=\"true\" element(s) contains focusable element(s).",
    remediation: "Fix the issue by removing aria-hidden=\"true\" for the focusable and interactive controls.\n\nReference:\nWAI-ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA input fields must have an accessible name",
    newSummary: "ARIA input fields are missing an accessible name",
    expectedResults: "The above-mentioned ARIA input field element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned ARIA input field element(s) is missing an accessible name.",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1. Explicit label: Under most circumstances, the best technique is to use the \u003clabel\u003e element with the for attribute. The value of the for attribute is the id attribute value of the \u003cinput\u003e element.\n\n\u003clabel for=\"fname\"\u003eFirst Name:\u003c/label\u003e \n\u003cinput type=\"text\" name=\"fn\" id=\"fname\"\u003e\n\n2. Use an aria-label attribute or title attribute on the \u003cinput\u003e to provide a label when there is no visible label.\n\n\u003cinput type=\"text\" aria-label=\"search\"\u003e\n \u003cinput type=\"submit\" value=\"Search\"\u003e\n\n3. Use an aria-labelledby attribute on the \u003cinput\u003e to reference a visible label. The value of the aria-labelledby attribute is the id attribute value of the visible text label.\n\n\u003cspan id=\"nickname\"\u003eNickname:\u003c/span\u003e\n\u003cinput type=\"text\" aria-labelledby=\"nickname\"\u003e\n\nIMPORTANT: If using aria-labelledby to associate form fields and a table header cell, the table headers/labels must be in \u003cspan\u003e elements inside the \u003cth\u003e. It is the \u003cspan\u003e element and NOT the \u003cth\u003e element that should have the referenced id. If you place the id on the \u003cth\u003e element, some screen readers will not read the labels correctly when you tab through the form elements.\n\n4. Implicit label (explicit label method is strongly preferred): Wrap the form element within the \u003clabel\u003e element.\n\n\u003clabel\u003eFirst Name: \u003cinput type=\"text\" name=\"fn\"\u003e\u003c/label\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/forms/labels/semantic-labels\nW3C-WAI tutorial: https://www.w3.org/WAI/tutorials/forms/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Elements must only use permitted ARIA attributes",
    newSummary: "Elements use the non-permitted ARIA attributes",
    expectedResults: "The above-mentioned element(s) uses only permitted ARIA attribute(s).\n\n[PLACEHOLDER ADD SUPPORTED ATTRIBUTE]",
    actualResults: "The above-mentioned element(s) contains non-permitted ARIA attribute(s).\n\n[PLACEHOLDER ADD SUPPORTED ATTRIBUTE]",
    remediation: "Fix this issue by using the appropriate ARIA roles, states, and properties. \n\nResource Link:\n- https://www.w3.org/TR/wai-aria-1.1/ \n- https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Required ARIA attributes must be provided",
    newSummary: "Required ARIA attribute missing",
    expectedResults: "The above-mentioned element(s) is provided with all required ARIA attribute(s).",
    actualResults: "The above-mentioned element(s) is missing required ARIA attribute(s).",
    remediation: "Fix this issue by using the appropriate ARIA roles, states, and properties.\n\nReference: \nWAI-ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA roles used must conform to valid values",
    newSummary: "ARIA roles does not contain valid values",
    expectedResults: "The above-mentioned element(s) is provided with a valid ARIA role.\n\n[PLACEHOLDER ADD SUPPORTED ROLE]",
    actualResults: "The above-mentioned element(s) contains an invalid ARIA role.\n\n[PLACEHOLDER ADD UNSUPPORTED ROLE]",
    remediation: "How To Fix: \nFix this issue by using the appropriate ARIA roles, states, and properties.\n\nReference: \nWAI-ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA attributes must conform to valid values",
    newSummary: "ARIA attributes does not contain valid values",
    expectedResults: "The above-mentioned ARIA attribute(s) is provided with a valid value.\n\n[PLACEHOLDER ADD SUPPORTED ATTRIBUTE VALUE]",
    actualResults: "The above-mentioned ARIA attribute(s) contains an invalid value.\n\n[PLACEHOLDER ADD UNSUPPORTED ATTRIBUTE VALUE]",
    remediation: "Fix the issue by ensuring the value inside each attribute is spelled correctly and corresponds to a valid value.\n\nFor example, aria-hidden=\"true\" would pass, but aria-hidden=\"rtue\" would fail, as would aria-hidden=\"pizza\".\n\nReference: \nWAI-ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "ARIA attributes must conform to valid names",
    newSummary: "ARIA attributes does not contain valid names",
    expectedResults: "The above-mentioned element(s) uses valid ARIA attribute name(s).",
    actualResults: "The above-mentioned element(s) contains invalid ARIA attribute name(s).",
    remediation: "Fix the issue by ensuring the value inside each attribute is spelt correctly and corresponds to a valid name.\n\nReference:\nWAI-ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Buttons must have discernible text",
    newSummary: "Button does not have a name",
    expectedResults: "The above-mentioned button element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned button element(s) is missing an accessible name.",
    remediation: "Fix this issue by using any of the following techniques:-\n1. Use the innertext of the \u003cbutton\u003e or role=\"button\" element\n\n\u003cbutton\u003eApply now!\u003c/button\u003e\n\n\u003cbutton class=\"apply-btn\"\u003e\u003cspan class=\"sr-text\"\u003eApply now!\u003c/span\u003e\u003c/button\u003e\n\n2. Use a non-empty aria-label attribute on the \u003cbutton\u003e or role=\"button\" element.\n\n\u003cbutton class=\"apply-btn\" aria-label=\"Apply now!\"\u003e\u003c/button\u003e\n\n\u003cspan role=\"button\" class=\"apply-btn\" aria-label=\"Apply Now!\"\u003e\u003c/span\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/custom-widgets/concepts/name\nW3C ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/#aria-label",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Frames must have an accessible name",
    newSummary: "Frames are missing an accessible name",
    expectedResults: "The above-mentioned frame element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned frame element(s) is missing an accessible name.",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1. Use the title attribute.\n\n\u003ciframe title=\"Video of touch screen for the blind in New York City taxis\" src=\"//www.youtube.com/embed/hM0x0k2Bv3Y\"\u003e\u003c/iframe\u003e\n\n2. Use an aria-labelledby attribute which references the id attribute of visible text on the screen.\n\n\u003ch3 id=\"ts-vid\"\u003eVideo of touch screen for the blind in New York City taxis\u003c/h3\u003e\n\u003ciframe src=\"//www.youtube.com/embed/hM0x0k2Bv3Y\" aria-labelledby=\"ts-vid\"\u003e\u003c/iframe\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/iframes/frame-titles",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Form elements must have labels",
    newSummary: "Form field is missing an accessible name",
    expectedResults: "The above-mentioned form field element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned form field element(s) is missing an accessible name.",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1. Explicit label: Under most circumstances, the best technique is to use the \u003clabel\u003e element with the for attribute. The value of the for attribute is the id attribute value of the \u003cinput\u003e element.\n\n\u003clabel for=\"fname\"\u003eFirst Name:\u003c/label\u003e \n\u003cinput type=\"text\" name=\"fn\" id=\"fname\"\u003e\n\n2. Use an aria-label attribute or title attribute on the \u003cinput\u003e to provide a label when there is no visible label.\n\n\u003cinput type=\"text\" aria-label=\"search\"\u003e\n \u003cinput type=\"submit\" value=\"Search\"\u003e\n\n3. Use an aria-labelledby attribute on the \u003cinput\u003e to reference a visible label. The value of the aria-labelledby attribute is the id attribute value of the visible text label.\n\n\u003cspan id=\"nickname\"\u003eNickname:\u003c/span\u003e\n\u003cinput type=\"text\" aria-labelledby=\"nickname\"\u003e\n\nIMPORTANT: If using aria-labelledby to associate form fields and a table header cell, the table headers/labels must be in \u003cspan\u003e elements inside the \u003cth\u003e. It is the \u003cspan\u003e element and NOT the \u003cth\u003e element that should have the referenced id. If you place the id on the \u003cth\u003e element, some screen readers will not read the labels correctly when you tab through the form elements.\n\n4. Implicit label (explicit label method is strongly preferred): Wrap the form element within the \u003clabel\u003e element.\n\n\u003clabel\u003eFirst Name: \u003cinput type=\"text\" name=\"fn\"\u003e\u003c/label\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/forms/labels/semantic-labels\nW3C-WAI tutorial: https://www.w3.org/WAI/tutorials/forms/",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Links must have discernible text",
    newSummary: "Link does not have discernible link text",
    expectedResults: "The above-mentioned link element(s) is provided with discernible link text.",
    actualResults: "The above-mentioned link element(s) is missing discernible link text.",
    remediation: "Fix this issue by using ONE of the following techniques:-\n\n1.Use link text contained between the opening \u003ca\u003e and closing \u003c/a\u003e elements. Link text can be: visible text, CSS clipped text, or alternative text on an \u003cimg\u003e element.\n\n\u003ca href=\"https://dequeuniversity.com/contact/\"\u003eContact Us\u003c/a\u003e\n\n\u003ca href=\"https://www.facebook.com/dequesystems/\" class=\"fbicon\"\u003e\u003cspan class=\"sr-text\"\u003eDeque\u0027s Facebook page\u003c/span\u003e\u003c/a\u003e\n\n\u003ca href=\"http://www.deque.com\"\u003e\u003cimg src=\"deque_logo.png\" alt=\"Deque Systems\"\u003e\u003c/a\u003e\n\n2. Use an aria-label attribute or an aria-labelledby attribute to name a link.\n\n\u003ca href=\"https://www.facebook.com/dequesystems/\" class=\"fbicon\" aria-label=\"Deque\u0027s Facebook page\"\u003e\u003c/a\u003e\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/links/link-text",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Interactive controls must not be nested",
    newSummary: "Interactive elements contain nested focusable elements",
    expectedResults: "The above-mentioned interactive element(s) does not contain nested interactive element(s).",
    actualResults: "The above-mentioned interactive element(s) contains nested interactive element(s).",
    remediation: "Fix this issue by ensuring that button and link elements do not contain other button or link elements or any other interactive elements.\n\nReference: \nDeque University: https://dequeuniversity.com/class/semantic-structure/parsing-and-validity/\nHTML5 spec: https://www.w3.org/TR/html52/sec-forms.html#the-button-element\nHTML5 spec: https://www.w3.org/TR/html52/textlevel-semantics.html#the-a-element",
  },
  {
    checkpoint: "4.1.2",
    oldSummary: "Select element must have an accessible name",
    newSummary: "Select element does not have an accessible name",
    expectedResults: "The above-mentioned select element(s) is provided with an accessible name.",
    actualResults: "The above-mentioned select element(s) is missing an accessible name.",
    remediation: "Fix this issue by using ONE of the following techniques:-\n1. Use an HTML \u003cselect\u003e element with \u003coption\u003e elements to create the drop-down menu.\n2. Use the ARIA combobox design pattern. View the full ARIA design pattern for a combobox including expected keyboard interactions and examples: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/\n\nReference: \nW3C HTML5 Recommendation: https://www.w3.org/TR/html5/sec-forms.html#the-select-element\nWAI-ARIA Authoring Practices: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
  },
];

if (typeof module !== 'undefined' && module.exports) { module.exports = { SUMMARY_MAP }; }
if (typeof window !== 'undefined') { window.SUMMARY_MAP = SUMMARY_MAP; }
